import { ChatMessage } from "./chatManager";

export type Platform = "local" | "kaggle" | "colab";
export type OutputFormat = "py" | "ipynb";
export type Architecture = "resnet" | "transformer" | "custom_cnn" | "mlp" | "custom";

export interface ScriptGenRequest {
  architecture: Architecture;
  task: string;
  platform: Platform;
  outputFormat: OutputFormat;
  epochs: number;
  optimizer: string;
  extraNotes: string;
}

const ARCH_HINTS: Record<Architecture, string> = {
  resnet: "ResNet-50 (torchvision.models.resnet50, pretrained=True) for image classification/fine-tuning",
  transformer: "Transformer encoder model for sequence classification or regression",
  custom_cnn: "Custom CNN with Conv2d → BatchNorm → ReLU → MaxPool → Linear layers",
  mlp: "Multi-layer perceptron (fully-connected layers with BatchNorm and Dropout)",
  custom: "User-defined architecture (provide a placeholder class)",
};

// No `pip install arc-training` here. The generated script never imports ARC —
// it is instrumented from the outside when run under ARC Lens — so telling a
// Kaggle or Colab user to install a package the script does not use implies a
// coupling that does not exist.
const PLATFORM_HEADERS: Record<Platform, string> = {
  local: "# Local GPU training script",
  kaggle: `# Kaggle GPU training script
# Paste into a Kaggle Notebook cell, or run as a script`,
  colab: `# Google Colab training script
# Paste into a Colab cell`,
};

/**
 * Builds the chat messages array for a script generation request.
 */
export function buildScriptGenMessages(req: ScriptGenRequest): ChatMessage[] {
  // The rules below deliberately do NOT tell the model to import or call into
  // ARC. ARC Lens instruments a script from the outside — `runner.py` installs
  // the hooks and then executes the user's file unmodified — so a generated
  // `import arc` / `arc.wrap(model)` would be a call into an API this project
  // does not expose. An earlier version of this prompt asked for exactly that,
  // and every script it produced carried a line that could only fail.
  const systemPrompt = `You are ARC Script Generator, an expert PyTorch engineer who writes clean, production-ready training scripts.

The script you produce will be run under ARC Lens, which monitors training and recovers it from failures. ARC instruments the script externally — it patches the optimizer at launch — so the script must contain NO ARC-specific imports, wrappers, decorators or callbacks. A plain, idiomatic PyTorch script is exactly what ARC needs.

## Rules for every script you generate:
1. Write ordinary PyTorch. No \`import arc\`, no \`arc.wrap(...)\`, no ARC callbacks.
2. Build the model, then the optimizer, then the training loop, in that order.
3. Call \`loss.backward()\` on a scalar loss and then \`optimizer.step()\`. ARC measures at \`optimizer.step()\`, so avoid \`torch.autograd.backward(loss)\` (the function form) — it is not observable.
4. If you use mixed precision, use \`scaler.scale(loss).backward()\` and \`scaler.step(optimizer)\`; ARC reads the unscaled loss from the scaler.
5. Include a try/except around the training loop to catch and log exceptions.
6. Include checkpoint logic: save model state_dict every N epochs using \`torch.save\`.
7. Optionally call \`arc_set_epoch(epoch)\` at the top of each epoch inside a \`try/except NameError\` — ARC injects it, and it labels the dashboard's x-axis. The script must run fine without it.
8. Add a \`# Generated by ARC Lens\` comment at the very top.
9. Keep the script clean, well-commented, and production-ready.

## Output format
- If outputFormat is "py": output a single complete Python script inside a \`\`\`python block
- If outputFormat is "ipynb": output a series of cells as JSON in \`\`\`json format following the Jupyter notebook v4 schema

Do NOT include any prose outside the code block. Just the code.`;

  const userPrompt = `Generate a complete PyTorch training script with the following specifications:

- **Architecture**: ${ARCH_HINTS[req.architecture]}
- **Task**: ${req.task}
- **Platform**: ${req.platform} — prepend: ${PLATFORM_HEADERS[req.platform]}
- **Output format**: ${req.outputFormat === "py" ? "Python .py script" : "Jupyter .ipynb notebook"}
- **Epochs**: ${req.epochs}
- **Optimizer**: ${req.optimizer} (with appropriate LR scheduler)
- **Extra requirements**: ${req.extraNotes || "None"}

Remember: plain PyTorch with no ARC imports, a scalar \`loss.backward()\` followed by \`optimizer.step()\`, and proper checkpointing.`;

  return [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];
}

/**
 * Extracts the code block from the LLM response.
 */
export function extractCodeBlock(response: string, format: OutputFormat): string | null {
  const lang = format === "py" ? "python" : "json";
  const regex = new RegExp("```" + lang + "\\s*([\\s\\S]*?)```", "i");
  const match = response.match(regex);
  if (match) return match[1].trim();
  // Fallback: return raw if no code fence found
  const anyFence = response.match(/```[\s\S]*?\n([\s\S]*?)```/);
  return anyFence ? anyFence[1].trim() : null;
}
