import { ChatMessage } from "./chatManager";

export type Platform = "local" | "kaggle" | "colab";
export type OutputFormat = "py" | "ipynb";
export type Architecture = "resnet" | "transformer" | "custom_cnn" | "mlp" | "custom";

export interface ScriptGenRequest {
  architecture: Architecture;
  task: string;
  platform: Platform;
  outputFormat: OutputFormat;
  epochs: number;
  optimizer: string;
  extraNotes: string;
}

const ARCH_HINTS: Record<Architecture, string> = {
  resnet: "ResNet-50 (torchvision.models.resnet50, pretrained=True) for image classification/fine-tuning",
  transformer: "Transformer encoder model for sequence classification or regression",
  custom_cnn: "Custom CNN with Conv2d → BatchNorm → ReLU → MaxPool → Linear layers",
  mlp: "Multi-layer perceptron (fully-connected layers with BatchNorm and Dropout)",
  custom: "User-defined architecture (provide a placeholder class)",
};

// No `pip install arc-training` here. The generated script never imports ARC —
// it is instrumented from the outside when run under ARC Lens — so telling a
// Kaggle or Colab user to install a package the script does not use implies a
// coupling that does not exist.
const PLATFORM_HEADERS: Record<Platform, string> = {
  local: "# Local GPU training script",
  kaggle: `# Kaggle GPU training script
# Paste into a Kaggle Notebook cell, or run as a script`,
  colab: `# Google Colab training script
# Paste into a Colab cell`,
};

/**
 * Builds the chat messages array for a script generation request.
 */
export function buildScriptGenMessages(req: ScriptGenRequest): ChatMessage[] {
  // The rules below deliberately do NOT tell the model to import or call into
  // ARC. ARC Lens instruments a script from the outside — `runner.py` installs
  // the hooks and then executes the user's file unmodified — so a generated
  // `import arc` / `arc.wrap(model)` would be a call into an API this project
  // does not expose. An earlier version of this prompt asked for exactly that,
  // and every script it produced carried a line that could only fail.
  const systemPrompt = `You are ARC Script Generator, an expert PyTorch engineer who writes clean, production-ready training scripts.

The script you produce will be run under ARC Lens, which monitors training and recovers it from failures. ARC instruments the script externally — it patches the optimizer at launch — so the script must contain NO ARC-specific imports, wrappers, decorators or callbacks. A plain, idiomatic PyTorch script is exactly what ARC needs.

## Rules for every script you generate:
1. Write ordinary PyTorch. No \`import arc\`, no \`arc.wrap(...)\`, no ARC callbacks.
2. Build the model, then the optimizer, then the training loop, in that order.
3. Call \`loss.backward()\` on a scalar loss and then \`optimizer.step()\`. ARC measures at \`optimizer.step()\`, so avoid \`torch.autograd.backward(loss)\` (the function form) — it is not observable.
4. If you use mixed precision, use \`scaler.scale(loss).backward()\` and \`scaler.step(optimizer)\`; ARC reads the unscaled loss from the scaler.
5. Include a try/except around the training loop to catch and log exceptions.
6. Include checkpoint logic: save model state_dict every N epochs using \`torch.save\`.
7. Optionally call \`arc_set_epoch(epoch)\` at the top of each epoch inside a \`try/except NameError\` — ARC injects it, and it labels the dashboard's x-axis. The script must run fine without it.
8. Add a \`# Generated by ARC Lens\` comment at the very top.
9. Keep the script clean, well-commented, and production-ready.

## Output format
- If outputFormat is "py": output a single complete Python script inside a \`\`\`python block
- If outputFormat is "ipynb": output one complete notebook object as JSON in a \`\`\`json block — an object with "cells", "metadata", "nbformat": 4 and "nbformat_minor", following the Jupyter notebook v4 schema. Not a bare array of cells.

Do NOT include any prose outside the code block. Just the code.`;

  const userPrompt = `Generate a complete PyTorch training script with the following specifications:

- **Architecture**: ${ARCH_HINTS[req.architecture]}
- **Task**: ${req.task}
- **Platform**: ${req.platform} — prepend: ${PLATFORM_HEADERS[req.platform]}
- **Output format**: ${req.outputFormat === "py" ? "Python .py script" : "Jupyter .ipynb notebook"}
- **Epochs**: ${req.epochs}
- **Optimizer**: ${req.optimizer} (with appropriate LR scheduler)
- **Extra requirements**: ${req.extraNotes || "None"}

Remember: plain PyTorch with no ARC imports, a scalar \`loss.backward()\` followed by \`optimizer.step()\`, and proper checkpointing.`;

  return [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];
}

/**
 * Validates extracted notebook text, returning the JSON to write or an error.
 *
 * Nothing checked the .ipynb path before this: whatever came out of the fence
 * was written straight to disk, so a trailing comma or a leaked sentence
 * produced a file Jupyter and VS Code both refuse to open — with a "saved"
 * toast claiming success. A bare `[...]` cell array is accepted and wrapped,
 * because that is the shape a model most often returns and rejecting it would
 * throw away a usable notebook over an envelope this function can supply.
 */
export function normalizeNotebook(text: string): { json: string } | { error: string } {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    return { error: `the model's notebook output is not valid JSON — ${(e as Error).message}` };
  }

  const nb: Record<string, unknown> = Array.isArray(parsed)
    ? { cells: parsed }
    : (parsed as Record<string, unknown>);

  if (!nb || typeof nb !== "object" || !Array.isArray(nb.cells)) {
    return { error: "the model's notebook output has no `cells` array." };
  }

  // Supply the envelope rather than demand it: nbformat/metadata are boilerplate
  // a model routinely omits, and their absence says nothing about the cells.
  nb.nbformat = typeof nb.nbformat === "number" ? nb.nbformat : 4;
  nb.nbformat_minor = typeof nb.nbformat_minor === "number" ? nb.nbformat_minor : 5;
  if (!nb.metadata || typeof nb.metadata !== "object") {
    nb.metadata = { kernelspec: { name: "python3", display_name: "Python 3", language: "python" } };
  }

  for (const cell of nb.cells as Array<Record<string, unknown>>) {
    if (!cell || typeof cell !== "object" || typeof cell.cell_type !== "string") {
      return { error: "the model's notebook contains a cell with no `cell_type`." };
    }
    if (typeof cell.source !== "string" && !Array.isArray(cell.source)) {
      return { error: `a ${cell.cell_type} cell has no \`source\`.` };
    }
    if (!cell.metadata || typeof cell.metadata !== "object") cell.metadata = {};
    if (cell.cell_type === "code") {
      if (!Array.isArray(cell.outputs)) cell.outputs = [];
      if (typeof cell.execution_count !== "number") cell.execution_count = null;
    }
  }

  return { json: JSON.stringify(nb, null, 1) };
}

/**
 * Extracts the code block from the LLM response.
 */
export function extractCodeBlock(response: string, format: OutputFormat): string | null {
  const lang = format === "py" ? "python" : "json";

  // The opening fence must run to end-of-line before the body starts.
  // "```" + lang + "\\s*" matched a *prefix* of the tag, so a response opening
  // ```python3 matched "python" and then `\s*` matched nothing, putting the
  // leftover "3" at the head of the extracted code — a valid script that then
  // failed py_compile on line 1.
  const fenced = new RegExp("```" + lang + "[^\\n]*\\n([\\s\\S]*)```", "i");
  const match = response.match(fenced);
  if (match) return match[1].trim();

  // Any fenced block, same greedy body.
  //
  // Both patterns are greedy to the *last* closing fence rather than the first.
  // A lazy body stops at the first ``` inside the block, which truncates any
  // notebook whose markdown cells contain a fenced snippet — routine in a
  // generated Colab notebook, and it produced invalid JSON saved as a corrupt
  // .ipynb. The trailing text after a final fence is prose we do not want, and
  // the model is asked for exactly one block, so the last fence is the right
  // terminator.
  const anyFence = response.match(/```[^\n]*\n([\s\S]*)```/);
  if (anyFence) return anyFence[1].trim();

  // No fence at all returns null, deliberately. A model that refuses ("I can't
  // help with that") or answers in prose would otherwise be written straight
  // into a .py or .ipynb file as though it were the generated script. The .py
  // path would at least fail the py_compile check downstream; the notebook path
  // has no such check. An honest "no code fence found" beats a file containing
  // an apology, so the cost — discarding a bare script from a model that took
  // "emit nothing but code" literally — is accepted.
  return null;
}
